#指定tomcat端口
server:
  port: 8082

#数据库连接池
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lancer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxwait: 10000

#mapper映射
mybatis:
  mapper-locations: classpath:mapping/*.xml
